### ISSUE TITLE
Rename istio chart to riff-istio or istio-riff

### ISSUE THREAD

**Issue by trisberg** [projectriff/charts#21]
Since istio chart is now installed separately it would be better to indicate that it is a riff specific chart, especially since we use riff versioning.

```
NAME      	REVISION	UPDATED                 	STATUS  	CHART                              	APP VERSION      	NAMESPACE        
istio     	1       	Wed Aug 14 14:14:11 2019	DEPLOYED	istio-0.4.0-snapshot               	1.1.13           	istio-system     
```

**Comment by scothis** [comment]
It previous had that name, because the charts are in the projectriff repository, you install it as `projectriff/riff-istio` which seemed a bit overkill.

It's also worth pointing out that we use the official Istio charts, the repackaging is to tweak the default values. The `appVersion` of the chart correctly reflects the Istio version.

**Comment by trisberg** [comment]
Maybe use the istio version for the chart then, like `istio-1.1.13`

IMO this looks better:
```NAME      	REVISION	UPDATED                 	STATUS  	CHART                 APP VERSION      	NAMESPACE        
istio     	1       	Wed Aug 14 15:44:16 2019	DEPLOYED	istio-1.1.13          1.1.13           	istio-system     
```

**Comment by scothis** [comment]
We're using [`appVersion`](https://helm.sh/docs/charts/#the-appversion-field) the way it's indeed to be used. The Istio and riff charts should be versioned together because the configurations and releases are tested and released together.
